name: 'Everyones Place '
favicon: null
layout_spectrum: 0.74292
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#d2d0d1'
    - '#a8a8a8'
    - '#787677'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
