name: 'Everyones Place '
favicon: null
layout_spectrum: 0.75181
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41303536016494036
  lightness: 0.2890574948396534
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
